users/urls.py
from django.urls import path
from django.conf import settings
from . import views
from users.views import Home, Contact, Signin, Signus, Slot, BrokerSignin,Slottable,Dailyrate

app_name = "users"

urlpatterns = [
    path('', Home.as_view(), name = "index"),
    path('contact', Contact.as_view(), name='contact'),
    path('signin', Signin.as_view(), name='signin' ),
    path('signup', Signus.as_view(), name='signus'),
    path('slot', Slot.as_view(), name='slot'),
    path('broker-signin', BrokerSignin.as_view(), name='agent'),
    path('table',Slottable.as_view(), name='table'),
    path('dailyrate', Dailyrate.as_view(), name='daily')
]

users/models.py
from django.db import models

# Create your models here.
class Table(models.Model):
    email = models.EmailField(max_length=100)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    crop_name = models.CharField(max_length=100)
    seed_type  = models.CharField(max_length=100)
    quality = models.CharField(max_length=25)
    quantity = models.IntegerField()
    date = models.DateField()
    time = models.TimeField()


users/views.py
import json
from pyexpat.errors import messages
from django.shortcuts import render,redirect
from django.views import View
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from . import models
from django.conf import settings
from django.core.mail import send_mail
from users.models import Table
import urllib.request




# Create your views here.
class Home(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'index.html')

class Contact(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'contactus.html')

class Signin(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'SignIn.html')

    def post(self, request, *args, **kwargs):
        username = request.POST['email']   
        password = request.POST['password']


        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return redirect(reverse('users:index'))
            else:
                print('TEST')
                messages.info(request, 'Inactive user')
                return redirect(reverse('users:contact'))
        return render(request, 'signus.html')

class Signus(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'SignUS.html')

    def post(self, request, *args, **kwargs):
        name = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']

        print(name,email,password)

        user = User.objects.create(username=name,email=email,password=password)
        user.save()
        return redirect(reverse('users:index'))

class Slot(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'slot.html')

    def post(self,request,*args,**kwargs):
        email = request.POST['email']
        cname = request.POST['cname']
        stype = request.POST['stype']
        qdrop = request.POST['qdrop']
        quantity = request.POST['quantity']
        date = request.POST['date']
        time = request.POST['time']
        price = request.POST['price']

        print(time,date)

        models.Table.objects.create(email=email, price=price, crop_name=cname,seed_type=stype,quality=qdrop,quantity=quantity,date=date, time=time)
        return redirect(reverse('users:index'))
        

class BrokerSignin(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'brokersignin.html')

    def post(self, request, *args, **kwargs):
        username = request.POST['email']   
        password = request.POST['password']


        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active and user.is_staff:
                login(request, user)
                return redirect(reverse('users:table'))
            else:
                print('TEST')
                messages.info(request, 'Inactive user')
                return redirect(reverse('users:contact'))
        return render(request, 'index.html')

class Slottable(View):
    def get(self, request, *args, **kwargs):
        slots = Table.objects.filter()
        return render(request, 'table.html', {"slots":slots})

    def post(self, request, *args, **kwargs):
        required = request.POST['submit']
        table = Table.objects.filter(pk=required)
        subject = 'welcome to GFG world'
        message = f'Dear Farmer,\n Slot confirmed with the APMC on day = {table[0].date} at time = {table[0].time}.\nPlease find the details below : \nCrop = {table[0].crop_name},Quantity={table[0].quantity}.'
        email_from = settings.EMAIL_HOST_USER
        recipient_list = [table[0].email, ]
        send_mail( subject, message, email_from, recipient_list )

        return render(request, 'index.html')

class Dailyrate(View):
    def get(self, request, *args, **kwargs):

        request_url = urllib.request.urlopen('https://api.data.gov.in/resource/9ef84268-d588-465a-a308-a864a43d0070?api-key=579b464db66ec23bdd000001cdd3946e44ce4aad7209ff7b23ac571b&format=json&limit=10&filters%5Bstate%5D=Maharashtra')
        data = request_url.read()
        JSON_object = json.loads(data.decode('utf-8'))
        return render(request, 'dailyRates.html', {'slots':JSON_object['records'][1::]})

users/templates/SignIn.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <!-- CSS only -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
  <!-- JavaScript Bundle with Popper -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3"
    crossorigin="anonymous"></script>
    <link rel="stylesheet" href={% static 'SignIn.css' %} />
    <link rel="stylesheet" href={% static 'index.css' %} />

  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Lobster&family=Source+Sans+Pro:wght@200&display=swap"
    rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="navbar.css">
    <link rel="stylesheet" href="./contactus.html">
    <link rel="stylesheet" href="login.php">
</head>

<body>
<!-- navbar -->
<nav class="navbar navbar-expand-lg sticky-top " id="navbar">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'users:index' %}">
      <img src="{% static 'img/kisan_shrikant_logo.png' %}" alt="Bootstrap" width="200px" height="80px">
    </a>
    <!-- <a class="navbar-brand" href="#">KisanSarthi</a> -->
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown"
      aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="nav navbar-nav ml-auto ">
        <li class="nav-item">
          <a class="nav-link " aria-current="page" href="{% url 'users:index' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link " aria-current="page" href="#about">About</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'users:slot' %}">Slot Booking</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'users:daily' %}">Daily Rate</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'users:agent' %}">Agent</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'users:contact' %}">Contact Us</a>
        </li>

        <li class="nav-item">
          <a href="{% url 'users:signus' %}" class="btn btn-outline-light" tabindex="-1" role="button" aria-disabled="true">Login</a>
        </li>

      </ul>
      </li>
      </ul>
    </div>

    </ul>
  </div>
  </div>
</nav>
<!-- navbar-end -->
  <div class="container-fluid " id="sign-in">
    
    <form action="#" method="POST"> 
      {% csrf_token %}
      
      <h3 class="display-6">SIGN IN</h3>
      <div class="mb-3">
        <label for="exampleInputEmail1" class="form-label">Username</label>
        <input type="text" placeholder="Username" class="form-control" id="exampleInputEmail1" name="email" aria-describedby="emailHelp">
      </div>
      <div class="mb-3">
        <label for="exampleInputPassword1" class="form-label">Password</label>
        <input type="password" placeholder="&#x1F512; Password" class="form-control" id="exampleInputPassword1" name="password">
        <input type="checkbox" id="exampleCheck1" onclick="myFunction()">
        <label class="form-check-label" for="exampleCheck1">show password</label>
      </div>
      <button type="submit" class="btn btn-primary">SIGN IN</button>
      <label class="form-check-label d-flex justify-content-center"  >Not have an account?&nbsp;<a href="{% url 'users:signus' %}"> SIGN UP </a></label>
    </form>
  </div> 
  
  
</body>
<script>
  function myFunction() {
  var x = document.getElementById("exampleInputPassword1");
  if (x.type === "password") {
    x.type = "text";
  } else {
    x.type = "password";
  }
}

</script>
</html>

users/templates/SignUS.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link rel="stylesheet" href="./SignUS.css">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
  <!-- JavaScript Bundle with Popper -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3"
    crossorigin="anonymous"></script>
    <link rel="stylesheet" href={% static 'SignUS.css' %} />
    <link rel="stylesheet" href={% static 'navbar.css' %} />
  <link rel="stylesheet" href="index.html">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Lobster&family=Source+Sans+Pro:wght@200&display=swap"
    rel="stylesheet">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Lobster&family=Source+Sans+Pro:wght@200&display=swap"
    rel="stylesheet">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="./contactus.html">
</head>

<body>
  <!-- navbar -->
  <nav class="navbar navbar-expand-lg sticky-top " id="navbar">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'users:index' %}">
       <img src="{% static 'img/kisan_shrikant_logo.png' %}" alt="Bootstrap" width="200px" height="80px">
      </a>
      <!-- <a class="navbar-brand" href="#">KisanSarthi</a> -->
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown"
        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="nav navbar-nav ml-auto ">
          <li class="nav-item">
            <a class="nav-link " aria-current="page" href="{% url 'users:index' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link " aria-current="page" href="#about">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:slot' %}">Slot Booking</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:daily' %}">Daily Rate</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:agent' %}">Agent</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:contact' %}">Contact Us</a>
          </li>

          <li class="nav-item">
            <a href="{% url 'users:signus' %}" class="btn btn-outline-light" tabindex="-1" role="button" aria-disabled="true">Login</a>
          </li>

        </ul>
        
      </div>

      </ul>
    </div>
    </div>
  </nav>
  <!-- navbar-end -->
  <div class="container-fluid" style="margin-top: 45px;" id="sign-in">
    <form action="#" method="POST">
      {% csrf_token %}
      <h3 class="display-6 container-fluid">SIGN UP</h3>
      <div class="mb-3 container-fluid">
        <label for="username" class="form-label">Username</label>
        <input type="text" placeholder="Username" class="form-control" name="username" id="username" aria-describedby="username">
      </div>

      <div class="mb-3 container-fluid">
        <label for="exampleInputEmail1" class="form-label">Email</label>
        <input type="email" placeholder="&#9993; Email" class="form-control" id="exampleInputEmail1" name="email"
          aria-describedby="emailHelp">
      </div>
      <div class="mb-3 container-fluid">
        <label for="exampleInputPassword1" class="form-label">Password</label>
        <input type="password" placeholder="&#x1F512; Password" class="form-control" id="exampleInputPassword1" name="password">
        <input type="checkbox" id="exampleCheck1" onclick="myFunction()">
        <label class="form-check-label" for="exampleCheck1">show password</label>
      </div>

      <div class="mb-3 container-fluid">
        <label for="birthdate" class="form-label">Birth Date</label>
        <input type="date" class="form-control" id="birthdate" aria-describedby="birthdate" name="birthdate">
      </div>
      <div class="mb-3 form-check container-fluid">
        <input type="checkbox" class="form-check-input" id="exampleCheck1">
        <label class="form-check-label" for="exampleCheck1">remember me?</label>
      </div>
      <button type="submit" class="btn btn-primary container-fluid">SIGN UP</button>
      <label class="form-check-label d-flex justify-content-center">Already have an account?&nbsp;<a
          href="{% url 'users:signin' %}"> SIGN IN</a></label>
    </form>
  </div>
</body>
<script>
  function myFunction() {
    var x = document.getElementById("exampleInputPassword1");
    if (x.type === "password") {
      x.type = "text";
    } else {
      x.type = "password";
    }
  }

</script>

</html>

users/templates/brokersignin.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <!-- CSS only -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
  <!-- JavaScript Bundle with Popper -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3"
    crossorigin="anonymous"></script>
    <link rel="stylesheet" href={% static 'navbar.css' %} />
    <link rel="stylesheet" href={% static 'SignIn.css' %} />

  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Lobster&family=Source+Sans+Pro:wght@200&display=swap"
    rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="./contactus.html">
    <link rel="stylesheet" href="login.php">
</head>

<body>
<!-- navbar -->
<nav class="navbar navbar-expand-lg sticky-top " id="navbar">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'users:index' %}">
      <img src="{% static 'img/kisan_shrikant_logo.png' %}" alt="Bootstrap" width="200px" height="80px">
    </a>
    <!-- <a class="navbar-brand" href="#">KisanSarthi</a> -->
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown"
      aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="nav navbar-nav ml-auto ">
        <li class="nav-item">
          <a class="nav-link " aria-current="page" href="{% url 'users:index' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link " aria-current="page" href="#about">About</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'users:slot' %}">Slot Booking</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'users:daily' %}">Daily Rate</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'users:contact' %}">Contact Us</a>
        </li>

        <li class="nav-item">
          <a href="{% url 'users:signus' %}" class="btn btn-outline-light" tabindex="-1" role="button" aria-disabled="true">Login</a>
        </li>

      </ul>
      </li>
      </ul>
    </div>

    </ul>
  </div>
  </div>
</nav>
<!-- navbar-end -->
  <div class="container-fluid " id="sign-in">
    
    <form action="#" method="POST"> 
      {% csrf_token %}
      
      <h3 class="display-6">AGENT SIGN IN</h3>
      <div class="mb-3">
        <label for="exampleInputEmail1" class="form-label">Username</label>
        <input type="text" placeholder="Username" class="form-control" id="exampleInputEmail1" name="email" aria-describedby="emailHelp">
      </div>
      <div class="mb-3">
        <label for="exampleInputPassword1" class="form-label">Password</label>
        <input type="password" placeholder="&#x1F512; Password" class="form-control" id="exampleInputPassword1" name="password">
        <input type="checkbox" id="exampleCheck1" onclick="myFunction()">
        <label class="form-check-label" for="exampleCheck1">show password</label>
      </div>
      <button type="submit" class="btn btn-primary">SIGN IN</button>
    </form>
  </div> 
  
  
</body>
<script>
  function myFunction() {
  var x = document.getElementById("exampleInputPassword1");
  if (x.type === "password") {
    x.type = "text";
  } else {
    x.type = "password";
  }
}

</script>
</html>

users/templates/contactus.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3"
        crossorigin="anonymous"></script>
        <link rel="stylesheet" href={% static 'contactus.css' %} />
        <link rel="stylesheet" href={% static 'navbar.css' %} />

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lobster&family=Source+Sans+Pro:wght@200&display=swap"
        rel="stylesheet">
    <link rel="stylesheet" href="">
<link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&display=swap" rel="stylesheet">
    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>

</head>

<body>
    <!-- navbar -->
  <nav class="navbar navbar-expand-lg sticky-top " id="navbar">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'users:index' %}">
        <img src="{% static 'img/kisan_shrikant_logo.png' %}" alt="Bootstrap" width="200px" height="80px">
      </a>
      <!-- <a class="navbar-brand" href="#">KisanSarthi</a> -->
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown"
        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="nav navbar-nav ml-auto ">
            <li class="nav-item">
                <a class="nav-link " aria-current="page" href="{% url 'users:index' %}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link " aria-current="page" href="#about">About</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'users:slot' %}">Slot Booking</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'users:daily' %}">Daily Rate</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'users:agent' %}">Agent</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'users:contact' %}">Contact Us</a>
              </li>
    
              <li class="nav-item">
                <a href="{% url 'users:signus' %}" class="btn btn-outline-light" tabindex="-1" role="button" aria-disabled="true">Login</a>
              </li>

        </ul>
        
      </div>

      </ul>
    </div>
    </div>
  </nav>
  <!-- navbar-end -->

    <div class="row">
        <div class="col-8">
            <div class="container-fluid" id="sign-in">
                <form>
                    <div class="row">
                        <h3 class="display-6 container-fluid">Get in Touch</h3>
                        <div class="col-6">

                            <div class="mb-3 container-fluid">
                                <label for="username" class="form-label">First Name</label>
                                <input type="text" placeholder="First Name" class="form-control" id="username"
                                    aria-describedby="username">
                            </div>
                            <div class="mb-3 container-fluid">
                                <label for="exampleInputEmail1" class="form-label">Email</label>
                                <input type="email" placeholder="&#9993; Email" class="form-control"
                                    id="exampleInputEmail1" aria-describedby="emailHelp">
                            </div>
                        </div>
                        <div class="col-6">
                            <div class="mb-3 container-fluid">
                                <label for="username" class="form-label">Last Name</label>
                                <input type="text" placeholder="Last Name" class="form-control" id="username"
                                    aria-describedby="username">
                            </div>

                            <div class="mb-3 container-fluid">
                                <label for="exampleInputEmail1" class="form-label">Mobile No.</label>
                                <input type="tel" placeholder="&#128379; Mobile No." class="form-control"
                                    id="exampleInputEmail1" aria-describedby="emailHelp">
                            </div>
                        </div>
                        <div class="form-floating">
                            <textarea class="form-control" placeholder="Write your message here..."
                                id="floatingTextarea2" style="height: 200px"></textarea>
                            <label for="floatingTextarea2">Message</label>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-primary container-fluid">Send</button>
                </form>
            </div>
        </div>
        <div class="col-4">
            <div class="container-fluid" id="contact-info">
                <div class="contact info">
                    <h3 class="display-6 container-fluid">Contact Info</h3>

                    <div>
                        <p>
                            <span>
                                <ion-icon name="location"></ion-icon>
                            </span>
                            Market Yard,Gultekadi,
                            Pune
                        </p>
                    </div>
                    <div>
                        <p>
                            <span>
                                <ion-icon name="mail"></ion-icon>
                            </span>
                            abc@gmail.com
                        </p>
                    </div>
                    <div>
                        <p>
                            <span>
                                <ion-icon name="call"></ion-icon>
                            </span>
                            +91 9875412647
                        </p>
                    </div>
                    <!-- Social media Links -->
                    <ul class="sci">
                        <a href="https://www.facebook.com/kisansarathi">
                                <ion-icon name="logo-facebook"></ion-icon>
                            </a>
                        <a href="https://twitter.com/KisanSarathi">
                            <ion-icon name="logo-twitter"></ion-icon>
                        </a>
                        <a href="https://www.linkedin.com/feed/">
                                <ion-icon name="logo-linkedin"></ion-icon>
                            </a>
                        <a href="https://www.instagram.com/i.am.shrikant_/">
                                <ion-icon name="logo-instagram"></ion-icon>
                        </a>
                    </ul>
                    <div class="contact-map">
                        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d7567.863629304333!2d73.86597362436179!3d18.48674749971456!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3bc2c020f86e3cc3%3A0xa796d6342ce667e5!2sMarket%20Yard%2C%20Gultekadi%2C%20Pune%2C%20Maharashtra%20411037!5e0!3m2!1sen!2sin!4v1671050515980!5m2!1sen!2sin" width="260" height="275" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
                </div>
            </div>
        </div>

</body>

</html>